using System;
using System.Collections.Generic;
using UnityEngine;

namespace _Scripts.TextComposition.Document
{
    /// <summary>
    /// A single word of the document. Tokens carry no whitespace and are
    /// non-empty by construction (ADR 0001); formatting attributes are added
    /// in a later slice.
    /// </summary>
    public sealed class WordToken
    {
        public string Text { get; }

        public WordToken(string text)
        {
            if (text == null)
                throw new ArgumentNullException(nameof(text));
            if (text.Length == 0)
                throw new ArgumentException("Word tokens must be non-empty", nameof(text));
            foreach (char c in text)
            {
                if (char.IsWhiteSpace(c))
                    throw new ArgumentException(
                        $"Word tokens must be single trimmed words, got '{text}'", nameof(text));
            }

            Text = text;
        }

        public override string ToString() => Text;
    }

    /// <summary>
    /// The word-token document model — the single source of truth for logical
    /// editor state (ADR 0001). Word boundaries are indices 0..WordCount:
    /// boundary k is before word k, boundary WordCount is after the last word.
    /// Separator blanks are never stored; they are generated by the compiler.
    /// </summary>
    public sealed class TextDocument
    {
        private readonly List<WordToken> words = new List<WordToken>();
        private readonly IReadOnlyList<WordToken> wordsView;

        public TextDocument()
        {
            wordsView = words.AsReadOnly();
        }

        /// <summary>
        /// Live read-only view of the word sequence. Consumers must treat it
        /// as immutable; all mutation goes through the methods below.
        /// </summary>
        public IReadOnlyList<WordToken> Words => wordsView;

        /// <summary>Raised after any mutation of the word sequence.</summary>
        public event Action Changed;

        /// <summary>
        /// Inserts one word — or a whitespace-separated run of words — at the
        /// given boundary. Insert must not trust prior state (delete is
        /// allowed to have left anything around): the text is trimmed at both
        /// ends, interior blanks split it into separate words, and each token
        /// is re-validated on the way in. Empty/whitespace-only input is
        /// misuse and fails loudly.
        /// </summary>
        /// <returns>The number of words actually inserted.</returns>
        public int InsertWord(int boundaryIndex, string text)
        {
            if (text == null)
                throw new ArgumentNullException(nameof(text));
            string trimmed = text.Trim();
            if (trimmed.Length == 0)
                throw new ArgumentException(
                    "InsertWord rejects empty (or whitespace-only) words", nameof(text));
            if (boundaryIndex < 0 || boundaryIndex > words.Count)
                throw new ArgumentOutOfRangeException(
                    nameof(boundaryIndex), boundaryIndex,
                    $"Boundary must be within [0, {words.Count}]");

            string[] parts = trimmed.Split((char[])null, StringSplitOptions.RemoveEmptyEntries);
            Debug.Assert(parts.Length > 0, "A non-empty trimmed text must split into at least one word");
            for (int i = 0; i < parts.Length; i++)
                words.Insert(boundaryIndex + i, new WordToken(parts[i]));

            Changed?.Invoke();
            return parts.Length;
        }

        /// <summary>
        /// Deletes the whole word before the given boundary — and with it the
        /// single separating blank, which the compiler regenerates on the
        /// next render. A no-op at the first boundary: deleting before
        /// nothing is valid state, not misuse. Out-of-range boundaries are
        /// misuse and fail loudly.
        /// </summary>
        public void DeletePrecedingWord(int boundaryIndex)
        {
            if (boundaryIndex < 0 || boundaryIndex > words.Count)
                throw new ArgumentOutOfRangeException(
                    nameof(boundaryIndex), boundaryIndex,
                    $"Boundary must be within [0, {words.Count}]");
            if (boundaryIndex == 0)
                return;

            words.RemoveAt(boundaryIndex - 1);
            Changed?.Invoke();
        }
    }
}
